"$schema" = 'https://starship.rs/config-schema.json'

# prompt options
add_newline = false

continuation_prompt = "[∙](bright-black) "

# prompt format
format = """
$directory\
$git_branch\
$git_status\
$git_state\
$conda\
$character"""

right_format = """
$cmd_duration\
"""

# modules options
[directory]
read_only = " 󰌾"
truncation_length = 5
truncate_to_repo = false

[git_branch]
symbol = " "
style = 'dimmed green'

[git_status]
format = '($all_status$ahead_behind )'
conflicted = '[${count}*](inverted red)'
ahead = '[${count}⇡](dimmed purple)'
behind = '[${count}⇣](inverted purple)'
diverged = '[${count}⇕](inverted green)'
untracked = '[${count}?](dimmed blue)'
stashed = '[${count}\$](dimmed cyan)'
modified = '[${count}!](dimmed yellow)'
staged = '[${count}+](green)'
renamed = '[${count}»](bright-cyan)'
deleted = '[${count}✘](dimmed red)'

[character]
success_symbol = '[➜](bold green)'

[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fossil_branch]
symbol = " "

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "

[pijul_channel]
symbol = " "

[python]
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "
