# vscode
- name: Check for vscode
  ansible.builtin.shell: command -v code
  register: vscode_exists
  ignore_errors: true

- name: Download latest vscode deb
  when: bottom_exists is failed
  ansible.builtin.get_url:
    url: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64
    dest: /tmp/vscode.deb

- name: Install vscode deb
  become: true
  when: vscode_exists is failed
  ansible.builtin.shell: dpkg -i /tmp/vscode.deb