# zsh ships with macOS — no need to install it

- name: Check for zsh
  ansible.builtin.shell: command -v zsh
  register: zsh_exists
  ignore_errors: yes

# install oh my zsh
- name: Install Oh My Zsh # noqa: latest
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: ~/.oh-my-zsh
    depth: 1
